### ISSUE TITLE
9x9 sgf

### ISSUE THREAD

**Issue by bdrose** [lightvector/leela-analysis#3]
I seem to be getting an error running on a 9x9 game generated from OGS. Here is a sample output followed by the files.

C:\Leela0100GTP\leela-analysis-master>sgfanalyze.py "9336957-056-Prester Jane-brose.sgf" --leela C:\Leela0100GTP\Leela0100GTP_OpenCL.exe > PresterJane-brose.sgf
Executing approx 168 analysis steps

|                                                  |   done% | Est... | done / total
|                                                  |   0.00% | Est... | 0 / 168
WARNING: analysis stats missing data mc_winrate
WARNING: analysis stats missing data nn_winrate
WARNING: analysis stats missing data margin
|                                                  |   0.60% | 0:37:51 | 1 / 166
WARNING: analysis stats missing data mc_winrate
WARNING: analysis stats missing data nn_winrate
WARNING: analysis stats missing data margin
|                                                  |   1.22% | 0:34:03 | 2 / 164

[9336957-056-Prester Jane-brose.sgf.txt](https://github.com/lightvector/leela-analysis/files/1133535/9336957-056-Prester.Jane-brose.sgf.txt)

[PresterJane-brose.sgf.txt](https://github.com/lightvector/leela-analysis/files/1133536/PresterJane-brose.sgf.txt)

**Comment by lightvector** [comment]
Thanks. It turns out that Leela doesn't have a neural net for non-19x19 board sizes, which breaks a bunch of the parsing which expects Leela to output various stats about its neural nets.

I pushed a fix to let the script handle Leela on these board sizes: https://github.com/lightvector/leela-analysis/commit/11e95dd2de966982f017c53b2226b6fe2a6bb5bf

Be aware that Leela will probably be much worse without a neural net. Even with the much smaller 9x9 board, Leela will probably not be as good on 9x9 as it is on 19x19. Among the three common board sizes, Leela's analysis will probably be the worst on 13x13.
